# Generated by Django 2.0.3 on 2018-04-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20180405_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentquestion',
            name='answer',
            field=models.TextField(default=1, verbose_name='답변'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequentquestion',
            name='question',
            field=models.TextField(default=1, verbose_name='질문'),
            preserve_default=False,
        ),
    ]
