# Generated by Django 2.0.3 on 2018-04-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_auto_20180405_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentquestion',
            name='subject2',
            field=models.CharField(default=1, max_length=20, verbose_name='소주제'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frequentquestion',
            name='subject',
            field=models.CharField(max_length=30, verbose_name='주제'),
        ),
    ]
