# Generated by Django 2.0.3 on 2018-04-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20180405_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentquestion',
            name='subject2',
            field=models.CharField(blank=True, max_length=20, verbose_name='소주제'),
        ),
    ]
