# Generated by Django 2.0.3 on 2018-04-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='img_thumbnail',
            field=models.ImageField(default=1, upload_to='blog-thumbnail'),
            preserve_default=False,
        ),
    ]
