# Generated by Django 2.0.3 on 2018-04-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20180406_1044'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='travel_Schedule',
        ),
        migrations.AddField(
            model_name='blog',
            name='travel_Reservation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reservation.Reservation'),
            preserve_default=False,
        ),
    ]
