# Generated by Django 2.0.3 on 2018-04-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Contents',
            new_name='contents',
        ),
    ]
