# Generated by Django 2.0.3 on 2018-04-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reversed_people',
            new_name='reserve_people',
        ),
    ]
