# Generated by Django 2.0.3 on 2018-04-02 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
        ('members', '0003_member'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='travel_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Travel_Information'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='travel_Schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Travel_Schedule'),
        ),
        migrations.AddField(
            model_name='recentvisitpage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='recentvisitpage',
            name='travel_Schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Travel_Schedule'),
        ),
    ]
