# Generated by Django 2.0.3 on 2018-04-11 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20180411_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserve_people',
            field=models.IntegerField(default=1, verbose_name='예약수'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='travel_Schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.TravelSchedule', verbose_name='travel_schedule'),
        ),
    ]
