# Generated by Django 2.0.3 on 2018-04-12 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0002_auto_20180412_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_products_info_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='travel_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_user_info_list', to='travel.TravelInformation'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('travel_info', 'member')},
        ),
    ]
