# Generated by Django 2.0.3 on 2018-04-12 06:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0003_auto_20180412_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='member',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('travel_info', 'user')},
        ),
    ]
