# Generated by Django 2.0.3 on 2018-04-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='price',
            new_name='total_price',
        ),
    ]
