# Generated by Django 2.0.3 on 2018-04-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mypoint',
        ),
    ]
