# Generated by Django 2.0.3 on 2018-04-09 05:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='user'),
        ),
    ]
