# Generated by Django 2.0.3 on 2018-04-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180409_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, default=1, upload_to='user', verbose_name='Profile'),
            preserve_default=False,
        ),
    ]
