# Generated by Django 2.0.3 on 2018-04-02 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180330_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, verbose_name='나이')),
                ('phonenumber', models.CharField(blank=True, max_length=15, verbose_name='전화번호')),
                ('email', models.CharField(max_length=30, verbose_name='이메일')),
                ('mypoint', models.IntegerField(default=0, verbose_name='내포인트')),
                ('mycoupon', models.IntegerField(default=0, verbose_name='내쿠폰')),
                ('isgetemail', models.BooleanField(default=True, verbose_name='메일수신여부체크')),
                ('isgetsms', models.BooleanField(default=True, verbose_name='sms수신여부체크')),
                ('isgetapppush', models.BooleanField(default=True, verbose_name='apppush수신여부체크')),
                ('isusable', models.BooleanField(default=True, verbose_name='사용여부')),
                ('creationdatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성시간')),
                ('modifydatetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='수정시간')),
            ],
        ),
    ]
