# Generated by Django 2.0.3 on 2018-04-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_user_mypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mypoint',
            field=models.IntegerField(default=0, verbose_name='내포인트'),
        ),
    ]
