# Generated by Django 2.0.3 on 2018-04-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_mypoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, default='default_img.png', upload_to='user', verbose_name='Profile'),
        ),
    ]
