# Generated by Django 2.0.3 on 2018-04-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180403_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to='user', verbose_name='Profile'),
        ),
    ]
