# Generated by Django 2.0.3 on 2018-04-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20180404_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mypoint',
            field=models.IntegerField(default=0, verbose_name='내포인트'),
        ),
    ]
