# Generated by Django 2.0.3 on 2018-04-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelinformationimage',
            old_name='img_field',
            new_name='product_image',
        ),
    ]
