# Generated by Django 2.0.3 on 2018-04-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinformation',
            name='description_title',
            field=models.TextField(blank=True, null=True, verbose_name='상품설명제목'),
        ),
    ]
