# Generated by Django 2.0.3 on 2018-04-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='여행끝날짜'),
        ),
    ]
