# Generated by Django 2.0.3 on 2018-04-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelschedule',
            name='is_possible_reservation',
            field=models.BooleanField(default=False),
        ),
    ]
