# Generated by Django 2.0.3 on 2018-04-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinformation',
            name='maxPeople',
            field=models.IntegerField(default=0, verbose_name='최대 사람 수'),
        ),
    ]
