# Generated by Django 2.0.3 on 2018-04-10 07:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinformationimage',
            name='product_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='product'),
        ),
    ]
