# Generated by Django 2.0.3 on 2018-04-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel_schedule',
            name='meetingTime',
        ),
        migrations.RemoveField(
            model_name='travel_schedule',
            name='member',
        ),
        migrations.RemoveField(
            model_name='travel_schedule',
            name='mettingPlace',
        ),
        migrations.AddField(
            model_name='travel_information',
            name='meetingTime',
            field=models.CharField(default=1, max_length=100, verbose_name='만남시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel_information',
            name='mettingPlace',
            field=models.CharField(default=1, max_length=100, verbose_name='만남장소'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travel_schedule',
            name='end_date',
            field=models.DateField(auto_now_add=True, verbose_name='여행끝날짜'),
        ),
    ]
