# Generated by Django 2.0.3 on 2018-04-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20180409_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelschedule',
            name='reversed_people',
            field=models.IntegerField(default=0, verbose_name='예약자수'),
        ),
    ]
