# Generated by Django 2.0.3 on 2018-04-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travelinformation_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinformation',
            name='main_image_thumbnail',
            field=models.ImageField(default=1, upload_to='main-image-thumbnail'),
            preserve_default=False,
        ),
    ]
