# Generated by Django 2.0.3 on 2018-04-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20180407_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinformationimage',
            name='image_id',
            field=models.ImageField(default=1, upload_to='', verbose_name='이미지 ID'),
            preserve_default=False,
        ),
    ]
