# Generated by Django 2.0.3 on 2018-04-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20180409_2143'),
        ('travel', '0002_auto_20180410_1632'),
    ]

    operations = [
    ]
