# Generated by Django 2.0.3 on 2018-04-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travelinformationimage_product_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityinformation',
            name='city_image_thumbnail',
            field=models.ImageField(default=1, upload_to='city-thumbnail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='company_image_thumbnail',
            field=models.ImageField(default=1, upload_to='company-thumbnail'),
            preserve_default=False,
        ),
    ]
