# Generated by Django 2.0.3 on 2018-04-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travelschedule_is_possible_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelschedule',
            name='is_possible_reservation',
            field=models.BooleanField(default=True),
        ),
    ]
