# Generated by Django 2.0.3 on 2018-04-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travelinformationimage_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinformationimage',
            name='image_id',
            field=models.IntegerField(verbose_name='이미지 ID'),
        ),
    ]
