# Generated by Django 2.0.3 on 2018-04-10 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0001_initial'),
        ('travel', '0003_travelschedule_reversed_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelschedule',
            name='reserved_user',
            field=models.ManyToManyField(blank=True, related_name='reserve_travel', through='reservation.Reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
