# Generated by Django 2.0.3 on 2018-04-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_merge_20180410_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinformationimage',
            name='product_image',
            field=models.ImageField(upload_to='product', verbose_name='상품이미지'),
        ),
    ]
