# Generated by Django 2.0.3 on 2018-04-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travelinformation_main_image_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelschedule',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='travelschedule',
            unique_together={('travel_info', 'start_date')},
        ),
    ]
