# Generated by Django 2.0.3 on 2018-04-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20180413_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelschedule',
            name='travel_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='travel.TravelInformation', verbose_name='schedules'),
        ),
    ]
