# Generated by Django 2.0.3 on 2018-04-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_travelschedule_reserved_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelschedule',
            old_name='reserved_user',
            new_name='travelschedule_user',
        ),
        migrations.AddField(
            model_name='travelschedule',
            name='reserved_people',
            field=models.IntegerField(default=0),
        ),
    ]
