# Generated by Django 2.0.3 on 2018-04-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20180407_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelschedule',
            name='maxPeople',
            field=models.IntegerField(default=1, verbose_name='최대 사람 수'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelschedule',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='여행끝날짜'),
        ),
        migrations.AlterField(
            model_name='travelschedule',
            name='start_date',
            field=models.DateField(verbose_name='여행시작날짜'),
        ),
    ]
