# Generated by Django 2.0.3 on 2018-04-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20180418_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelschedule',
            name='travel_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_info', to='travel.TravelInformation', verbose_name='travel_info'),
        ),
    ]
