# Generated by Django 2.0.3 on 2018-04-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20180407_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinformation',
            name='language',
            field=models.CharField(max_length=40, verbose_name='언어'),
        ),
        migrations.AlterField(
            model_name='travelinformation',
            name='time',
            field=models.CharField(max_length=40, verbose_name='소요시간'),
        ),
    ]
