# Generated by Django 2.0.3 on 2018-04-09 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20180407_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityinformation',
            name='city_image',
            field=models.ImageField(default=1, upload_to='city', verbose_name='도시이미지'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='company_image',
            field=models.ImageField(default=1, upload_to='company', verbose_name='회사이미지'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelinformationimage',
            name='travel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.TravelInformation'),
        ),
    ]
